import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Book Review',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* insert here Navbar */}
        <p>Hello</p>
        {children}

        {/* insert here footer */}
        </body>
    </html>
  )
}
